[package]
name = "mqtli"
version = "0.3.0"
edition = "2021"
description = "MQTT multi-topic and payload converting cli client"
license-file = "LICENSE.md"
repository = "https://github.com/kaans/mqtli"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mqtlib"
path = "src/lib.rs"

[[bin]]
name = "mqtli"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive", "env"] }
derive-getters = "0.5.0"
log = "0.4.22"
rumqttc = { git = "https://github.com/bytebeamio/rumqtt.git", rev = "431be1b", features = ["websocket"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.30"
simplelog = { version = "0.12.2", features = ["paris"] }
thiserror = "2.0.6"
tokio = { version = "1.42.0", features = ["macros", "rt", "rt-multi-thread", "sync", "signal"] }
validator = { version = "0.19.0", features = ["derive"] }
serde_json = "1.0.133"
base64 = "0.22.1"
hex = "0.4.3"
rustls-pemfile = "1.0.4"
regex = "1.11.1"
lazy_static = { version = "1.5.0", features = [] }
async-trait = { version = "0.1.83", features = [] }
protobuf = { version = "3.7.1", features = ["with-bytes"] }
protobuf-parse = "3.7.1"
protobuf-json-mapping = "3.7.1"
tokio-cron-scheduler = { version = "0.13.0", features = [] }
uuid = { version = "1.11.0", features = ["v4"] }
colored = "2.1.0"
strum_macros = "0.26.4"
