[package]
name = "mqtli"
version = "0.1.0"
edition = "2021"
description = "MQTT cli client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive", "env"] }
derive-getters = "0.3.0"
log = "0.4.20"
rumqttc = "0.23.0"
simplelog = "0.12.1"
tokio = { version = "1.34.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
