host: "localhost"
port: 8883
client_id: "mqtcli"
#keep_alive: "5"
#username: ""
#password: ""

use_tls: false
#tls_ca_file: "ca.crt"
#tls_client_certificate: "client.crt"
#tls_client_key: "client.key"

log_level: "info"

topics:
  - topic: mqtli/test
    subscription:
      enabled: true
      qos: 1
    payload:
      type: protobuf
      definition: "messages.proto"
      message: "Proto.Response"
    output:
      format: json #plain, yaml, hex, base64