broker:
  client_id: "my_client_id"
  username: "yourusernamehere"
  password: "yourpasswordhere"

  use_tls: false

  last_will:
    topic: "mqtli/lwt"
    payload: "Good bye"

topics:
  - topic: mqtli/test
    subscription:
      enabled: true
      qos: 1
      outputs:
        - format:
            type: yaml # target is console; protobuf message will be shown as yaml
        - format:
            type: base64
          target:
            type: file
            path: "log.txt"
            overwrite: false
            prepend: "MESSAGE: " # prepends the string "MESSAGE: " to the beginning of the base64 encoded message
            append: "\n" # appends a new line to the end of the message
    payload:
      type: text
    publish:
      enabled: true
      input:
        type: hex
        content: AB23F6E983 # this must be a valid protobuf message according to the payload format (encoded as hex)
      trigger:
        - type: periodic # default trigger: periodic with no count (indefinitely) and interval 1 second
